---
apiVersion: v1
kind: Service
metadata:
  name: questionario
  namespace: conformidade
  labels:
    app: questionario
spec:
  type: NodePort
  ports:
  - name: web
    port: 8082
    #targetPort: 8080
    nodePort: 30089
    protocol: TCP    
  selector:
    app: questionario
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: questionario
  namespace: conformidade
  labels:
    app: questionario
spec:
  replicas: 1
  selector:
    matchLabels:
      app: questionario
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: questionario 
    spec:
      containers:
      - name: questionario-api
        resources:
          limits:
            memory: "500Mi"
            cpu: "300m"
          requests:
            memory: "300Mi"
            cpu: "200m"
        image: 585849681126.dkr.ecr.us-east-2.amazonaws.com/ms-questionario:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
          name: web
          protocol: TCP    
#        readinessProbe:
#            httpGet:
#              path: /conformidade/v1/questionarios/actuator/health/readiness
#              port: 8082
#            failureThreshold: 1
#            periodSeconds: 1
#        livenessProbe:
#            httpGet:
#              path: /conformidade/v1/questionarios/actuator/health/liveness
#              port: 8082
#            failureThreshold: 1
#            initialDelaySeconds: 8
#            periodSeconds: 1
