---
apiVersion: v1
kind: Service
metadata:
  name: inspecao
  namespace: conformidade
  labels:
    app: inspecao
spec:
  type: NodePort
  ports:
  - name: web
    port: 8081
    #targetPort: 8080
    nodePort: 30088
    protocol: TCP    
  selector:
    app: inspecao
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inspecao
  namespace: conformidade
  labels:
    app: inspecao
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inspecao
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: inspecao 
    spec:
      containers:
      - name: inspecao-api
        resources:
          limits:
            memory: "500Mi"
            cpu: "300m"
          requests:
            memory: "300Mi"
            cpu: "200m"
        image: 585849681126.dkr.ecr.us-east-2.amazonaws.com/ms-inspecao:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 8081
          name: web
          protocol: TCP    
#        readinessProbe:
#            httpGet:
#              path: /conformidade/v1/inspecaos/actuator/health/readiness
#              port: 8082
#            failureThreshold: 1
#            periodSeconds: 1
#        livenessProbe:
#            httpGet:
#              path: /conformidade/v1/inspecaos/actuator/health/liveness
#              port: 8082
#            failureThreshold: 1
#            initialDelaySeconds: 8
#            periodSeconds: 1